# Generated by Django 6.0.2 on 2026-08-12 15:57

import datetime
import django.db.models.deletion
import django.utils.timezone
import sms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('reminder_type', models.CharField(choices=[('feeding', 'Feeding'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('sensor_check', 'Sensor Checking'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('message', models.TextField(help_text='SMS text to send at the scheduled time')),
                ('schedule_time', models.TimeField(help_text='Local time to send the reminder')),
                ('days_of_week', models.JSONField(default=list, help_text='Day numbers to send on (0=Sunday, 6=Saturday); empty = every day')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Reminder',
                'verbose_name_plural': 'SMS Reminders',
                'ordering': ['schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for all outgoing SMS')),
                ('recipient_number', models.CharField(blank=True, help_text='Mobile number that receives SMS (PH format, e.g. 09171234567)', max_length=20)),
                ('daily_enabled', models.BooleanField(default=False)),
                ('daily_time', models.TimeField(default=datetime.time(7, 0), help_text='Local time to send the daily summary')),
                ('alerts_enabled', models.BooleanField(default=True)),
                ('alert_min_severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='high', help_text='Only alerts at or above this severity are texted', max_length=20)),
                ('alert_types', models.JSONField(blank=True, default=sms.models.default_alert_types, help_text='Notification types that trigger an SMS alert')),
                ('alert_cooldown_minutes', models.PositiveIntegerField(default=10, help_text='Suppress repeat SMS of the same alert type within this many minutes')),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'SMS Settings',
                'verbose_name_plural': 'SMS Settings',
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_type', models.CharField(choices=[('daily', 'Daily Summary'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('test', 'Test')], db_index=True, max_length=20)),
                ('recipient', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='security.notification')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='sms.smsreminder')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='sms_smslog_created_77a93c_idx'), models.Index(fields=['sms_type', '-created_at'], name='sms_smslog_sms_typ_acfc5a_idx'), models.Index(fields=['status', '-created_at'], name='sms_smslog_status_31d19e_idx')],
            },
        ),
    ]
