# Generated by Django 6.0.2 on 2026-09-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Philippine mobile number, e.g. 09171234567 or +639171234567', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Allow this number to be used by account-related SMS features.')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_registration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Registration',
                'verbose_name_plural': 'SMS Registrations',
            },
        ),
    ]
