# Generated by Django 5.0.14 on 2025-12-20 07:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goat_id', models.CharField(help_text='Unique identifier (e.g., tag number, RFID)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for the goat', max_length=100)),
                ('tag_number', models.CharField(blank=True, help_text='Physical tag/ear tag number', max_length=50)),
                ('breed', models.CharField(choices=[('boer', 'Boer'), ('saanen', 'Saanen'), ('alpine', 'Alpine'), ('nubian', 'Nubian'), ('toggenburg', 'Toggenburg'), ('lamancha', 'LaMancha'), ('anglo_nubian', 'Anglo-Nubian'), ('native', 'Native/Local Breed'), ('mixed', 'Mixed Breed'), ('other', 'Other')], default='native', max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text='Approximate or exact date of birth', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Current weight in kilograms', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('monitoring', 'Under Monitoring'), ('sick', 'Sick'), ('quarantine', 'Quarantined')], default='healthy', max_length=20)),
                ('health_notes', models.TextField(blank=True, help_text='Any health observations or medical notes')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if goat has been sold, died, or removed')),
            ],
            options={
                'ordering': ['goat_id'],
                'indexes': [models.Index(fields=['goat_id'], name='iot_goat_goat_id_316de0_idx'), models.Index(fields=['is_active', 'health_status'], name='iot_goat_is_acti_f7e1d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrassHealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Area/zone where grass was analyzed', max_length=200)),
                ('greenness_index', models.FloatField(help_text='0-1 scale, derived from RGB analysis', validators=[django.core.validators.MinValueValidator(0)])),
                ('vegetation_density', models.FloatField(blank=True, help_text='0-1 scale, coverage percentage', null=True)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('drought', 'Drought Stressed')], default='fair', max_length=20)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('soil_moisture_percent', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grass_health/%Y/%m/%d/')),
                ('analyzed_by', models.CharField(help_text='Camera/device that captured the image', max_length=100)),
                ('analysis_data', models.JSONField(blank=True, help_text='Detailed computer vision analysis results', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='iot_grasshe_locatio_c77246_idx'), models.Index(fields=['health_status', '-timestamp'], name='iot_grasshe_health__2341f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoatBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('grazing', 'Grazing'), ('resting', 'Resting'), ('walking', 'Walking'), ('running', 'Running'), ('eating', 'Eating (at feeder)'), ('drinking', 'Drinking'), ('standing', 'Standing/Idle'), ('lying', 'Lying Down'), ('abnormal', 'Abnormal Behavior'), ('inactive', 'Inactive/Lethargic')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='ML model confidence (0-1)', validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('humidity_percent', models.FloatField(blank=True, null=True)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('detected_by', models.CharField(help_text='Camera/device that made the detection', max_length=100)),
                ('detection_data', models.JSONField(blank=True, help_text='Additional ML detection metadata', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('goat', models.ForeignKey(blank=True, help_text='Specific goat if identified, null for group behavior', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='iot.goat')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['goat', '-timestamp'], name='iot_goatbeh_goat_id_a2c347_idx'), models.Index(fields=['behavior_type', '-timestamp'], name='iot_goatbeh_behavio_e0d339_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload goat image', upload_to='goat_images/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('profile', 'Profile Picture'), ('full_body', 'Full Body'), ('face', 'Face/Muzzle'), ('identification', 'Identification Reference'), ('health', 'Health Documentation'), ('training', 'ML Training Data')], default='identification', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Has this image been processed by ML models?')),
                ('is_training_data', models.BooleanField(default=False, help_text='Use this image for ML model training')),
                ('detected_features', models.JSONField(blank=True, help_text='ML-extracted features (embeddings, keypoints, etc.)', null=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='iot.goat')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['goat', '-uploaded_at'], name='iot_goatima_goat_id_96a2b8_idx'), models.Index(fields=['is_training_data'], name='iot_goatima_is_trai_d6f093_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Humidity percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('soil_moisture', models.FloatField(blank=True, help_text='Soil moisture percentage (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('light_intensity', models.FloatField(blank=True, help_text='Light intensity (lux or arbitrary units)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_readings', to='iot.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='iot_sensorr_device__b7eb15_idx')],
            },
        ),
    ]
