# Generated by Django 5.1.15 on 2026-01-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_goat_grasshealthlog_goatbehaviorlog_goatimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(help_text='Unique camera identifier (e.g., CAM001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Descriptive camera name (e.g., 'Barn Entrance Cam')", max_length=200)),
                ('camera_type', models.CharField(choices=[('wifi', 'WiFi IP Camera'), ('rtsp', 'RTSP Camera'), ('http', 'HTTP/MJPEG Camera'), ('usb', 'USB Camera')], default='wifi', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='Camera IP address (e.g., 192.168.1.100)')),
                ('port', models.IntegerField(default=80, help_text='Camera port (usually 80, 554 for RTSP, or 8080)')),
                ('username', models.CharField(blank=True, help_text='Camera login username (if required)', max_length=100)),
                ('password', models.CharField(blank=True, help_text='Camera login password (if required)', max_length=100)),
                ('rtsp_url', models.CharField(blank=True, help_text='Full RTSP URL (e.g., rtsp://192.168.1.100:554/stream)', max_length=500)),
                ('http_url', models.CharField(blank=True, help_text='HTTP/MJPEG stream URL (e.g., http://192.168.1.100/video)', max_length=500)),
                ('snapshot_url', models.CharField(blank=True, help_text='URL for single snapshot (e.g., http://192.168.1.100/snapshot.jpg)', max_length=500)),
                ('location', models.CharField(help_text="Physical location (e.g., 'Barn Entrance', 'Feeding Area')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional notes about camera placement and purpose')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Connection Error')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this camera')),
                ('enable_goat_detection', models.BooleanField(default=True, help_text='Run ML goat detection on this camera feed')),
                ('detection_interval_seconds', models.IntegerField(default=30, help_text='How often to run detection (in seconds)')),
                ('last_connected', models.DateTimeField(blank=True, help_text='Last successful connection timestamp', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if connection failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['location', 'name'],
                'indexes': [models.Index(fields=['camera_id'], name='iot_ipcamer_camera__3e42e8_idx'), models.Index(fields=['is_active', 'status'], name='iot_ipcamer_is_acti_afc96b_idx')],
            },
        ),
    ]
