# Generated by Django 6.0.1 on 2026-02-13 13:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_ipcamera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_type', models.CharField(choices=[('door', 'Automated Door'), ('light', 'Automated Light')], max_length=20)),
                ('current_state', models.CharField(choices=[('on', 'ON'), ('off', 'OFF'), ('open', 'Open'), ('closed', 'Closed')], default='off', max_length=10)),
                ('mode', models.CharField(choices=[('manual', 'Manual Control'), ('auto', 'Automatic')], default='auto', help_text='Manual or Automatic control mode', max_length=10)),
                ('last_changed_at', models.DateTimeField(auto_now=True)),
                ('last_triggered_by', models.CharField(blank=True, help_text='User, rule, or system that triggered last state change', max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actuator_state', to='iot.device')),
            ],
            options={
                'verbose_name': 'Actuator State',
                'verbose_name_plural': 'Actuator States',
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name/description', max_length=200)),
                ('rule_type', models.CharField(choices=[('time_based', 'Time-Based (Schedule)'), ('sensor_based', 'Sensor-Based (Environmental)'), ('detection_based', 'Detection-Based (Goat Count)'), ('light_intensity', 'Light Intensity')], max_length=30)),
                ('action', models.CharField(choices=[('open_door', 'Open Door'), ('close_door', 'Close Door'), ('turn_on_light', 'Turn ON Light'), ('turn_off_light', 'Turn OFF Light')], max_length=30)),
                ('criteria', models.JSONField(default=dict, help_text="Conditions for rule trigger (e.g., {'time': '06:00', 'goat_count': '>10', 'temperature': '<25'})")),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules execute first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='iot.device')),
            ],
            options={
                'verbose_name': 'Automation Rule',
                'verbose_name_plural': 'Automation Rules',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActuationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Opened'), ('close', 'Closed'), ('turn_on', 'Turned ON'), ('turn_off', 'Turned OFF')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual Control'), ('rule', 'Automation Rule'), ('system', 'System'), ('api', 'API Call')], default='manual', max_length=20)),
                ('triggered_by', models.CharField(blank=True, help_text='User name, rule name, or system process', max_length=200)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional context (sensor values, goat count, etc.)', null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuation_logs', to='iot.device')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='iot.automationrule')),
            ],
            options={
                'verbose_name': 'Actuation Log',
                'verbose_name_plural': 'Actuation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='iot_actuati_device__47d2fb_idx'), models.Index(fields=['source', '-timestamp'], name='iot_actuati_source_c69870_idx')],
            },
        ),
    ]
