# Generated by Django 6.0.1 on 2026-02-23 03:06

import django.core.validators
from django.db import migrations, models


def assign_temporary_mac_addresses(apps, schema_editor):
    """Assign unique temporary MAC addresses to existing cameras"""
    IPCamera = apps.get_model('iot', 'IPCamera')
    for index, camera in enumerate(IPCamera.objects.all(), start=1):
        # Generate unique temporary MAC address
        camera.mac_address = f'00:00:00:00:00:{index:02X}'
        camera.save(update_fields=['mac_address'])


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_actuatorstate_automationrule_actuationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcamera',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', help_text='Camera MAC address (e.g., AA:BB:CC:DD:EE:FF) - Permanent identifier', max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF or AA-BB-CC-DD-EE-FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.RunPython(assign_temporary_mac_addresses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ipcamera',
            name='mac_address',
            field=models.CharField(help_text='Camera MAC address (e.g., AA:BB:CC:DD:EE:FF) - Permanent identifier', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF or AA-BB-CC-DD-EE-FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Current IP address (auto-discovered from MAC, or manually set)', null=True),
        ),
        migrations.AddIndex(
            model_name='ipcamera',
            index=models.Index(fields=['mac_address'], name='iot_ipcamer_mac_add_c88e6c_idx'),
        ),
    ]
