# Generated by Django 6.0.1 on 2026-02-23 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_ipcamera_mac_address_alter_ipcamera_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcamera',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='Camera IP address (e.g., 192.168.1.100)'),
        ),
        migrations.AlterField(
            model_name='ipcamera',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Optional: Camera MAC address for auto IP discovery when IP changes', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address (e.g., AA:BB:CC:DD:EE:FF or AA-BB-CC-DD-EE-FF)', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
    ]
