# Generated by Django 6.0.2 on 2026-03-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0006_alter_ipcamera_ip_address_alter_ipcamera_mac_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensorreading",
            name="feeder_level",
            field=models.FloatField(
                blank=True,
                help_text="Feeder level from ultrasonic sensor (distance in cm)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sensorreading",
            name="rain_detected",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Rain sensor status (True = raining, False = dry)",
                null=True,
            ),
        ),
    ]
