# Generated by Django 6.0.2 on 2026-03-01 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0007_sensorreading_feeder_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actuatorstate",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actuator_states",
                to="iot.device",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actuatorstate",
            unique_together={("device", "actuator_type")},
        ),
    ]
