# Generated by Django 6.0.2 on 2026-03-16 14:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_alter_actuatorstate_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this goat was registered in the system'),
        ),
        migrations.AddField(
            model_name='goat',
            name='inventory_status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('dead', 'Dead'), ('missing', 'Missing')], db_index=True, default='active', help_text='Farm inventory status managed by admin', max_length=20),
        ),
        migrations.AddField(
            model_name='goat',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Latest timestamp this goat was identified by AI', null=True),
        ),
        migrations.AlterField(
            model_name='actuationlog',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Control'), ('rule', 'Automation Rule'), ('system', 'System'), ('api', 'API Call'), ('physical_button', 'Physical Button'), ('esp32_sync', 'ESP32 Sync')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='actuatorstate',
            name='actuator_type',
            field=models.CharField(choices=[('door', 'Automated Door'), ('light', 'Automated Light'), ('feeder', 'Servo Feeder')], max_length=20),
        ),
        migrations.CreateModel(
            name='GoatDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(blank=True, help_text='Tracker-assigned ID for temporal consistency', max_length=100)),
                ('bbox', models.JSONField(default=dict, help_text='Bounding box coordinates and dimensions')),
                ('detection_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('similarity_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to='goat_detections/%Y/%m/%d/frames/')),
                ('crop_image', models.ImageField(blank=True, null=True, upload_to='goat_detections/%Y/%m/%d/crops/')),
                ('is_unknown', models.BooleanField(default=False)),
                ('auto_registered', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goat_detection_events', to='iot.ipcamera')),
                ('goat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='iot.goat')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='iot_goatdet_timesta_389254_idx'), models.Index(fields=['goat', '-timestamp'], name='iot_goatdet_goat_id_8cb454_idx'), models.Index(fields=['is_unknown', '-timestamp'], name='iot_goatdet_is_unkn_58b506_idx'), models.Index(fields=['track_id', '-timestamp'], name='iot_goatdet_track_i_2dc03a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoatEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.JSONField(help_text='Numeric embedding vector used for similarity matching')),
                ('model_name', models.CharField(default='reid_default', max_length=100)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('quality_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_reference', models.BooleanField(default=True, help_text='Use this embedding for identity matching')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='iot.goat')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goat', '-created_at'], name='iot_goatemb_goat_id_f7ccd0_idx'), models.Index(fields=['is_reference', '-created_at'], name='iot_goatemb_is_refe_5e974b_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoatPresenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_count', models.IntegerField(default=0)),
                ('recognized_active_count', models.IntegerField(default=0)),
                ('unknown_count', models.IntegerField(default=0)),
                ('expected_active_count', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('missing_goat_ids', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_snapshots', to='iot.ipcamera')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='iot_goatpre_timesta_b1ab88_idx'), models.Index(fields=['missing_count', '-timestamp'], name='iot_goatpre_missing_ab9e81_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissingGoatAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_count', models.IntegerField(default=0)),
                ('detected_count', models.IntegerField(default=0)),
                ('missing_goat_ids', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_goat_alerts', to='iot.ipcamera')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='iot_missing_status_e6b96c_idx'), models.Index(fields=['-created_at'], name='iot_missing_created_35634e_idx')],
            },
        ),
    ]
