# Generated by Django 6.0.2 on 2026-03-18 14:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0009_goat_date_registered_goat_inventory_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoatDetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bounding_box",
                    models.JSONField(
                        help_text="Bounding box coordinates: {x, y, width, height}"
                    ),
                ),
                (
                    "detection_confidence",
                    models.FloatField(
                        help_text="YOLOv8 detection confidence (0-1)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "identification_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Re-identification confidence score (0-1)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "feature_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Feature embedding vector extracted from this detection",
                        null=True,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True,
                        help_text="Cosine similarity score with matched goat",
                        null=True,
                    ),
                ),
                (
                    "is_new_goat",
                    models.BooleanField(
                        default=False,
                        help_text="True if this detection resulted in auto-registration",
                    ),
                ),
                (
                    "crop_image",
                    models.ImageField(
                        blank=True,
                        help_text="Cropped image of detected goat",
                        null=True,
                        upload_to="detection_crops/%Y/%m/%d/",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Goat Detection History",
                "verbose_name_plural": "Goat Detection Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("missing_goat", "Missing Goat Alert"),
                            ("health", "Health Alert"),
                            ("door_automation", "Door Automation"),
                            ("system", "System Notification"),
                            ("detection", "Detection Event"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("websocket", "WebSocket (Dashboard)"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("in_app", "In-App Notification"),
                        ],
                        default="websocket",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "recipient",
                    models.CharField(
                        help_text="Email address, phone number, or user ID",
                        max_length=200,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was successfully sent",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if delivery failed"
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0, help_text="Number of delivery attempts"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional notification data", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="goatdetectionevent",
            name="iot_goatdet_timesta_389254_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatdetectionevent",
            name="iot_goatdet_goat_id_8cb454_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatdetectionevent",
            name="iot_goatdet_is_unkn_58b506_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatdetectionevent",
            name="iot_goatdet_track_i_2dc03a_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatembedding",
            name="iot_goatemb_goat_id_f7ccd0_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatembedding",
            name="iot_goatemb_is_refe_5e974b_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatpresencesnapshot",
            name="iot_goatpre_timesta_b1ab88_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatpresencesnapshot",
            name="iot_goatpre_missing_ab9e81_idx",
        ),
        migrations.AlterModelOptions(
            name="missinggoatalert",
            options={
                "ordering": ["-triggered_at"],
                "verbose_name": "Missing Goat Alert",
                "verbose_name_plural": "Missing Goat Alerts",
            },
        ),
        migrations.RemoveIndex(
            model_name="missinggoatalert",
            name="iot_missing_status_e6b96c_idx",
        ),
        migrations.RemoveIndex(
            model_name="missinggoatalert",
            name="iot_missing_created_35634e_idx",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="date_registered",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="inventory_status",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="last_seen_at",
        ),
        migrations.AddField(
            model_name="goat",
            name="auto_registered",
            field=models.BooleanField(
                default=False,
                help_text="True if this goat was automatically registered by AI system",
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="embedding_last_updated",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the feature embedding was updated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="feature_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Feature embedding vector for re-identification (128-dim or 1280-dim)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time this goat was detected by AI system",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="registration_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score at the time of registration (0-1)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("sold", "Sold"),
                    ("dead", "Dead"),
                    ("missing", "Missing"),
                ],
                db_index=True,
                default="active",
                help_text="Current status of the goat in inventory",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="goatimage",
            name="embedding_extracted",
            field=models.BooleanField(
                default=False,
                help_text="Has feature embedding been extracted from this image?",
            ),
        ),
        migrations.AddField(
            model_name="goatimage",
            name="feature_embedding",
            field=models.JSONField(
                blank=True,
                help_text="Feature embedding vector extracted from this image",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("count_mismatch", "Count Mismatch"),
                    ("not_seen_recently", "Not Seen Recently"),
                    ("door_automation", "Door Automation Check"),
                    ("manual", "Manual Alert"),
                ],
                default="count_mismatch",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="automation_action_taken",
            field=models.CharField(
                blank=True,
                help_text="Action taken by automation system (e.g., 'door_hold', 'door_closed')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="is_resolved",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Has this alert been resolved?"
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="missing_count",
            field=models.IntegerField(
                default=0, help_text="Number of missing goats (expected - detected)"
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="missing_goats",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific goats identified as missing",
                related_name="missing_alerts",
                to="iot.goat",
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="notification_sent",
            field=models.BooleanField(
                default=False, help_text="Has notification been sent?"
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="resolution_notes",
            field=models.TextField(
                blank=True, help_text="Notes about how the alert was resolved"
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="resolved_by",
            field=models.CharField(
                blank=True,
                help_text="User or system that resolved the alert",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Alert title/summary",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="missinggoatalert",
            name="triggered_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="actuationlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Control"),
                    ("rule", "Automation Rule"),
                    ("system", "System"),
                    ("api", "API Call"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="missinggoatalert",
            name="detected_count",
            field=models.IntegerField(help_text="Number of goats actually detected"),
        ),
        migrations.AlterField(
            model_name="missinggoatalert",
            name="expected_count",
            field=models.IntegerField(help_text="Expected number of active goats"),
        ),
        migrations.AlterField(
            model_name="missinggoatalert",
            name="message",
            field=models.TextField(help_text="Detailed alert message"),
        ),
        migrations.AlterField(
            model_name="missinggoatalert",
            name="metadata",
            field=models.JSONField(
                blank=True,
                help_text="Additional context data (detection results, environmental conditions, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="missinggoatalert",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, help_text="When the alert was resolved", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="goat",
            index=models.Index(fields=["status"], name="iot_goat_status_983446_idx"),
        ),
        migrations.AddIndex(
            model_name="goat",
            index=models.Index(
                fields=["last_seen"], name="iot_goat_last_se_9b6055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goat",
            index=models.Index(
                fields=["auto_registered"], name="iot_goat_auto_re_771224_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goatimage",
            index=models.Index(
                fields=["embedding_extracted"], name="iot_goatima_embeddi_ad5339_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missinggoatalert",
            index=models.Index(
                fields=["-triggered_at"], name="iot_missing_trigger_b6463e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="missinggoatalert",
            index=models.Index(
                fields=["is_resolved", "-triggered_at"],
                name="iot_missing_is_reso_ec435a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missinggoatalert",
            index=models.Index(
                fields=["severity", "-triggered_at"],
                name="iot_missing_severit_2f2aa4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="missinggoatalert",
            index=models.Index(
                fields=["alert_type"], name="iot_missing_alert_t_e79f31_idx"
            ),
        ),
        migrations.AddField(
            model_name="goatdetectionhistory",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goat_detections",
                to="iot.ipcamera",
            ),
        ),
        migrations.AddField(
            model_name="goatdetectionhistory",
            name="goat",
            field=models.ForeignKey(
                blank=True,
                help_text="Identified goat (null if unidentified)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detection_history",
                to="iot.goat",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="iot.missinggoatalert",
            ),
        ),
        migrations.RemoveField(
            model_name="goatdetectionevent",
            name="camera",
        ),
        migrations.RemoveField(
            model_name="goatdetectionevent",
            name="goat",
        ),
        migrations.RemoveField(
            model_name="goatembedding",
            name="goat",
        ),
        migrations.RemoveField(
            model_name="goatpresencesnapshot",
            name="camera",
        ),
        migrations.RemoveField(
            model_name="missinggoatalert",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="missinggoatalert",
            name="missing_goat_ids",
        ),
        migrations.RemoveField(
            model_name="missinggoatalert",
            name="status",
        ),
        migrations.AddIndex(
            model_name="goatdetectionhistory",
            index=models.Index(
                fields=["goat", "-timestamp"], name="iot_goatdet_goat_id_231604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goatdetectionhistory",
            index=models.Index(
                fields=["camera", "-timestamp"], name="iot_goatdet_camera__e16794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goatdetectionhistory",
            index=models.Index(
                fields=["-timestamp"], name="iot_goatdet_timesta_3135f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goatdetectionhistory",
            index=models.Index(
                fields=["is_new_goat"], name="iot_goatdet_is_new__8bd8ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["-created_at"], name="iot_notific_created_d1535d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status", "-created_at"], name="iot_notific_status_0b01e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["channel", "-created_at"], name="iot_notific_channel_5bc6ae_idx"
            ),
        ),
        migrations.DeleteModel(
            name="GoatDetectionEvent",
        ),
        migrations.DeleteModel(
            name="GoatEmbedding",
        ),
        migrations.DeleteModel(
            name="GoatPresenceSnapshot",
        ),
    ]
