# Generated by Django 6.0.2 on 2026-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0011_goatownership"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="goatownership",
            name="iot_goatown_owner_i_31f6c1_idx",
        ),
        migrations.RemoveIndex(
            model_name="goatownership",
            name="iot_goatown_goat_id_95ff8f_idx",
        ),
        migrations.RemoveConstraint(
            model_name="goatownership",
            name="unique_goat_owner_pair",
        ),
        migrations.RemoveIndex(
            model_name="goat",
            name="iot_goat_auto_re_771224_idx",
        ),
        migrations.AddField(
            model_name="goat",
            name="color_markings",
            field=models.CharField(
                blank=True,
                help_text="Coat color and distinctive markings (e.g., brown with white patch on forehead)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="next_due_date",
            field=models.DateField(
                blank=True,
                help_text="Date the next vaccination is due (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="notes",
            field=models.TextField(
                blank=True, help_text="General notes or remarks about this goat"
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="vaccination_date",
            field=models.DateField(
                blank=True,
                help_text="Date the most recent vaccine was administered",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="vaccination_status",
            field=models.CharField(
                choices=[
                    ("not_vaccinated", "Not Vaccinated"),
                    ("partially_vaccinated", "Partially Vaccinated"),
                    ("fully_vaccinated", "Fully Vaccinated"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Overall vaccination status",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="goat",
            name="vaccine_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the most recent vaccine administered",
                max_length=150,
            ),
        ),
        migrations.RemoveField(
            model_name="goat",
            name="auto_registered",
        ),
        migrations.RemoveField(
            model_name="goat",
            name="registration_confidence",
        ),
        migrations.DeleteModel(
            name="GoatOwnership",
        ),
    ]
