# Generated by Django 6.0.2 on 2026-08-18 05:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0014_sensorreading_indoor_environment_sensors"),
    ]

    operations = [
        migrations.CreateModel(
            name="BLETrackingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "smoothing_method",
                    models.CharField(
                        choices=[
                            ("median", "Rolling Median"),
                            ("moving_average", "Moving Average"),
                        ],
                        default="median",
                        max_length=20,
                    ),
                ),
                (
                    "smoothing_window_size",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                ("very_near_min_rssi", models.SmallIntegerField(default=-50)),
                ("near_min_rssi", models.SmallIntegerField(default=-60)),
                ("medium_min_rssi", models.SmallIntegerField(default=-70)),
                (
                    "possibly_lost_timeout_seconds",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "out_of_range_timeout_seconds",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[django.core.validators.MinValueValidator(2)],
                    ),
                ),
                (
                    "report_interval_seconds",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                (
                    "heartbeat_interval_seconds",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "history_snapshot_interval_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "history_retention_days",
                    models.PositiveIntegerField(
                        default=90,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "BLE Tracking Settings",
                "verbose_name_plural": "BLE Tracking Settings",
            },
        ),
        migrations.CreateModel(
            name="BLEBeacon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(blank=True, max_length=100)),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="Optional platform-visible BLE address. Stored in uppercase colon format.",
                        max_length=17,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid MAC address (for example AA:BB:CC:DD:EE:FF).",
                                regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                            )
                        ],
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        help_text="Canonical iBeacon proximity UUID.", max_length=36
                    ),
                ),
                (
                    "major",
                    models.PositiveSmallIntegerField(
                        help_text="Farm or herd identifier (0-65535).",
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    "minor",
                    models.PositiveSmallIntegerField(
                        help_text="Individual beacon/goat identifier (0-65535).",
                        validators=[django.core.validators.MaxValueValidator(65535)],
                    ),
                ),
                (
                    "calibrated_rssi",
                    models.SmallIntegerField(
                        default=-59,
                        help_text="Measured RSSI at one metre, in dBm.",
                        validators=[
                            django.core.validators.MinValueValidator(-127),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "advertising_interval_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Configured advertising interval in milliseconds, when known.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(10240),
                        ],
                    ),
                ),
                (
                    "tx_power_dbm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Configured transmitter power in dBm, when known.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "battery_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Most recently reported battery percentage, when advertised.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("battery_updated_at", models.DateTimeField(blank=True, null=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goat",
                    models.OneToOneField(
                        blank=True,
                        help_text="Goat currently assigned to this tracker. Trackers may remain unassigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ble_beacon",
                        to="iot.goat",
                    ),
                ),
            ],
            options={
                "verbose_name": "BLE Beacon",
                "verbose_name_plural": "BLE Beacons",
                "ordering": ["device_name", "major", "minor"],
            },
        ),
        migrations.CreateModel(
            name="BLEReceiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("windows", "Windows"),
                            ("linux", "Linux"),
                            ("raspberry_pi", "Raspberry Pi"),
                            ("other", "Other"),
                        ],
                        default="windows",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="Operating-system device or host name.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "last_online",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("scanner_version", models.CharField(blank=True, max_length=50)),
                (
                    "api_key_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="One-way hash of the receiver ingestion credential.",
                        max_length=128,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ble_receiver",
                        to="iot.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "BLE Receiver",
                "verbose_name_plural": "BLE Receivers",
                "ordering": ["device__name"],
            },
        ),
        migrations.CreateModel(
            name="BLEObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rssi",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-127),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "smoothed_rssi",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-127),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                (
                    "proximity",
                    models.CharField(
                        choices=[
                            ("very_near", "Very Near"),
                            ("near", "Near"),
                            ("medium", "Medium"),
                            ("far", "Far"),
                            ("out_of_range", "Out of Range"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "beacon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="iot.blebeacon",
                    ),
                ),
                (
                    "goat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assignment snapshot retained if the beacon is later reassigned.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ble_observations",
                        to="iot.goat",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="iot.blereceiver",
                    ),
                ),
            ],
            options={
                "verbose_name": "BLE Observation",
                "verbose_name_plural": "BLE Observations",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="BLETrackingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_rssi",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-127),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "smoothed_rssi",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-127),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "proximity",
                    models.CharField(
                        choices=[
                            ("very_near", "Very Near"),
                            ("near", "Near"),
                            ("medium", "Medium"),
                            ("far", "Far"),
                            ("out_of_range", "Out of Range"),
                        ],
                        db_index=True,
                        default="out_of_range",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("possibly_lost", "Possibly Lost"),
                            ("out_of_range", "Out of Range"),
                        ],
                        db_index=True,
                        default="out_of_range",
                        max_length=20,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beacon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_states",
                        to="iot.blebeacon",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_states",
                        to="iot.blereceiver",
                    ),
                ),
            ],
            options={
                "verbose_name": "BLE Tracking State",
                "verbose_name_plural": "BLE Tracking States",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddIndex(
            model_name="blebeacon",
            index=models.Index(
                fields=["uuid", "major", "minor"], name="iot_blebeac_uuid_cf7af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blebeacon",
            index=models.Index(
                fields=["enabled", "updated_at"], name="iot_blebeac_enabled_79ee08_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="blebeacon",
            constraint=models.UniqueConstraint(
                fields=("uuid", "major", "minor"), name="unique_ibeacon_identity"
            ),
        ),
        migrations.AddIndex(
            model_name="bleobservation",
            index=models.Index(
                fields=["beacon", "receiver", "-detected_at"],
                name="iot_bleobse_beacon__1c9189_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bleobservation",
            index=models.Index(
                fields=["goat", "-detected_at"], name="iot_bleobse_goat_id_9cf3c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bletrackingstate",
            index=models.Index(
                fields=["receiver", "status", "-last_seen"],
                name="iot_bletrac_receive_903820_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bletrackingstate",
            index=models.Index(
                fields=["beacon", "-last_seen"], name="iot_bletrac_beacon__eb2aa7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bletrackingstate",
            constraint=models.UniqueConstraint(
                fields=("beacon", "receiver"), name="unique_ble_beacon_receiver_state"
            ),
        ),
    ]
