# Generated by Django 6.0.2 on 2026-08-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0010_favorites_reports_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending review"),
                    ("approved", "Approved Seller"),
                    ("rejected", "Declined"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
