# Generated by Django 6.0.2 on 2026-08-24 14:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import marketplace.models
from django.conf import settings
from django.db import migrations, models


def backfill_registered_user_administration(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserAccountState = apps.get_model("marketplace", "UserAccountState")
    UserActivity = apps.get_model("marketplace", "UserActivity")
    states = []
    activities = []
    for user in User.objects.all().iterator():
        states.append(
            UserAccountState(
                user_id=user.pk,
                status="active" if user.is_active else "deactivated",
            )
        )
        activities.append(
            UserActivity(
                user_id=user.pk,
                event="account_registered",
                description="Account registered.",
                created_at=user.date_joined,
            )
        )
    UserAccountState.objects.bulk_create(states, ignore_conflicts=True)
    UserActivity.objects.bulk_create(activities, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_alter_sellerprofile_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplacenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("inquiry", "Inquiry"),
                    ("message", "Message"),
                    ("reservation", "Reservation"),
                    ("pickup", "Pickup"),
                    ("sale", "Sale"),
                    ("seller_review", "Seller review"),
                    ("report", "Listing report"),
                    ("listing", "Listing"),
                    ("support", "Customer support"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=5000)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=marketplace.models.PrivateSupportStorage(),
                        upload_to=marketplace.models.support_attachment_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "pdf"]
                            ),
                            marketplace.models.validate_support_attachment_size,
                        ],
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="marketplace.supportmessage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("account", "Account Concern"),
                            ("seller_application", "Seller Application"),
                            ("marketplace", "Marketplace Concern"),
                            ("reservation", "Reservation / Purchase Concern"),
                            ("technical", "Technical Issue"),
                            ("report_user", "Report User / Seller"),
                            ("other", "Other Concern"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(max_length=5000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("waiting_customer", "Waiting for Customer"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=12,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="marketplace.conversation",
                    ),
                ),
                (
                    "related_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="marketplace.marketplacelisting",
                    ),
                ),
                (
                    "related_reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to="marketplace.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="supportmessage",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="marketplace.supportticket",
            ),
        ),
        migrations.AddField(
            model_name="marketplacenotification",
            name="support_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="marketplace.supportticket",
            ),
        ),
        migrations.CreateModel(
            name="UserAccountState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deactivated", "Deactivated"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, max_length=1000)),
                ("changed_at", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_state_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marketplace_account_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(db_index=True, max_length=60)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="important_activity_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="important_account_activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User activity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(
            backfill_registered_user_administration,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["user", "status", "-updated_at"], name="support_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["status", "priority", "-updated_at"], name="support_queue_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["category", "-created_at"], name="support_category_idx"
            ),
        ),
    ]
