# Generated by Django 5.0.14 on 2025-12-20 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='input_size',
            field=models.JSONField(default=dict, help_text="Model input dimensions, e.g., {'width': 640, 'height': 640}"),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='Model accuracy (0-1)', null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='file_path',
            field=models.CharField(help_text='Path to model file (.h5, .pt, .pkl)', max_length=500),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('yolo', 'YOLO (TensorFlow/Keras)'), ('pytorch', 'PyTorch Model'), ('sklearn', 'scikit-learn'), ('tensorflow', 'TensorFlow/Keras')], default='yolo', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('name', 'version')},
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('goat_count', models.IntegerField(default=0)),
                ('confidence', models.FloatField(help_text='Average confidence score (0-1)')),
                ('bounding_boxes', models.JSONField(default=list, help_text='List of detected boxes: [{x, y, width, height, confidence, class}]')),
                ('processed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(limit_choices_to={'device_type': 'camera'}, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='iot.device')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['camera', '-timestamp'], name='ml_models_d_camera__34de3b_idx'), models.Index(fields=['-timestamp'], name='ml_models_d_timesta_a0190e_idx')],
            },
        ),
    ]
