# Generated by Django 6.0.2 on 2026-03-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0003_remove_prediction_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mlmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("yolov8", "YOLOv8 (Ultralytics)"),
                    ("yolo", "YOLO (TensorFlow/Keras)"),
                    ("pytorch", "PyTorch Model"),
                    ("sklearn", "scikit-learn"),
                    ("tensorflow", "TensorFlow/Keras"),
                ],
                default="yolo",
                max_length=100,
            ),
        ),
    ]
