# Generated by Django 6.0.2 on 2026-03-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0010_goatdetectionhistory_notificationlog_and_more"),
        ("ml_models", "0004_alter_mlmodel_model_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="detection",
            name="ml_models_d_camera__34de3b_idx",
        ),
        migrations.AlterField(
            model_name="detection",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"device_type": "camera"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detections",
                to="iot.device",
            ),
        ),
    ]
