# Generated by Django 6.0.2 on 2026-08-08 15:18

import django.db.models.deletion
import ml_models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_models", "0005_remove_detection_ml_models_d_camera__34de3b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("goat", "Goat Detection"),
                    ("person", "Person Detection"),
                    ("face", "Face Detection"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="goat",
                help_text="What this model detects",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="file_size",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Size of the uploaded file in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="model_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded, validated model file (stored privately)",
                null=True,
                storage=ml_models.models._protected_model_storage,
                upload_to="%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded (pending validation)"),
                    ("validated", "Validated"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                    ("rejected", "Rejected (failed validation)"),
                ],
                db_index=True,
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_ml_models",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="validation_notes",
            field=models.TextField(
                blank=True, help_text="Result of automatic/manual validation checks"
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="file_path",
            field=models.CharField(
                blank=True,
                help_text="Path to model file (.h5, .pt, .pkl). Legacy/manual entries.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mlmodel",
            name="model_type",
            field=models.CharField(
                choices=[
                    ("yolov8", "YOLOv8 (Ultralytics)"),
                    ("roboflow", "Roboflow Inference (Self-hosted)"),
                    ("roboflow-hosted", "Roboflow Hosted API"),
                    ("yolo", "YOLO (TensorFlow/Keras)"),
                    ("pytorch", "PyTorch Model"),
                    ("sklearn", "scikit-learn"),
                    ("tensorflow", "TensorFlow/Keras"),
                ],
                default="yolo",
                max_length=100,
            ),
        ),
    ]
