from django.urls import path
from allauth.account import views as account_views

from . import views

app_name = "marketplace"

urlpatterns = [
    path("", views.marketplace_landing, name="landing"),
    path("goats/", views.marketplace_list, name="list"),
    path(
        "login/",
        account_views.LoginView.as_view(template_name="marketplace/login.html"),
        name="buyer_login",
    ),
    path(
        "register/",
        account_views.SignupView.as_view(template_name="marketplace/register.html"),
        name="register",
    ),
    path("profile/complete/", views.complete_profile, name="complete_profile"),
    path("seller/apply/", views.seller_application, name="seller_application"),
    path("seller/dashboard/", views.seller_dashboard, name="seller_dashboard"),
    path("seller/goats/", views.seller_goats, name="seller_goats"),
    path("seller/goats/add/", views.seller_goat_manage, name="seller_goat_add"),
    path("seller/goats/<int:pk>/edit/", views.seller_goat_manage, name="seller_goat_edit"),
    path("seller/goats/<int:goat_pk>/images/<int:image_pk>/delete/", views.seller_goat_image_delete, name="seller_goat_image_delete"),
    path("seller/listings/", views.seller_listings, name="seller_listings"),
    path("seller/listings/add/", views.seller_listing_manage, name="seller_listing_add"),
    path("seller/listings/<int:pk>/edit/", views.seller_listing_manage, name="seller_listing_edit"),
    path("seller/listings/<int:pk>/publication/", views.seller_listing_publication, name="seller_listing_publication"),
    path("seller/<int:pk>/", views.seller_public_profile, name="seller_profile"),
    path("inquiries/", views.my_inquiries, name="my_inquiries"),
    path("seller/messages/", views.seller_messages, name="seller_messages"),
    path("seller/reservations/", views.seller_reservations, name="seller_reservations"),
    path("seller/sales/", views.seller_sales_history, name="seller_sales_history"),
    path("reservations/", views.buyer_reservations, name="buyer_reservations"),
    path("purchases/", views.buyer_purchase_history, name="buyer_purchase_history"),
    path("saved/", views.saved_goats, name="saved_goats"),
    path("notifications/", views.notifications, name="notifications"),
    path("notifications/read-all/", views.notifications_read_all, name="notifications_read_all"),
    path("notifications/<int:pk>/open/", views.notification_open, name="notification_open"),
    path("support/", views.support_center, name="support_center"),
    path("support/new/", views.support_ticket_create, name="support_ticket_create"),
    path("support/<str:ticket_number>/", views.support_ticket_detail, name="support_ticket_detail"),
    path("support/attachment/<int:pk>/", views.support_attachment_download, name="support_attachment_download"),
    path("listing/<int:pk>/", views.listing_detail, name="detail"),
    path("listing/<int:pk>/inquire/", views.start_inquiry, name="start_inquiry"),
    path("listing/<int:pk>/favorite/", views.toggle_favorite, name="toggle_favorite"),
    path("listing/<int:pk>/report/", views.report_listing, name="report_listing"),
    path("conversation/<int:pk>/", views.conversation_detail, name="conversation"),
    path("conversation/<int:pk>/status/", views.conversation_status, name="conversation_status"),
    path("conversation/<int:pk>/reserve/", views.confirm_purchase, name="confirm_purchase"),
    path("reservation/<int:pk>/pickup/", views.pickup_request, name="pickup"),
    path("reservation/<int:pk>/action/", views.reservation_action, name="buyer_seller_reservation_action"),
    path("manage/", views.admin_dashboard, name="admin_dashboard"),
    path("manage/users/", views.registered_users_admin, name="registered_users_admin"),
    path("manage/users/<int:pk>/", views.registered_user_detail_admin, name="registered_user_detail_admin"),
    path("manage/users/<int:pk>/action/", views.registered_user_action_admin, name="registered_user_action_admin"),
    path("manage/support/", views.admin_support_tickets, name="admin_support_tickets"),
    path("manage/support/<str:ticket_number>/", views.admin_support_ticket_detail, name="admin_support_ticket_detail"),
    path("manage/sellers/", views.seller_applications_admin, name="seller_applications_admin"),
    path("manage/sellers/<int:pk>/action/", views.seller_application_action, name="seller_application_action"),
    path("manage/listing/add/", views.manage_listing, name="listing_add"),
    path("manage/listing/<int:pk>/edit/", views.manage_listing, name="listing_edit"),
    path("manage/listing/<int:pk>/publication/", views.set_listing_publication, name="listing_publication"),
    path("manage/listing/<int:pk>/feature/", views.set_listing_featured, name="listing_featured"),
    path("manage/inquiries/", views.admin_inquiries, name="admin_inquiries"),
    path("manage/reports/", views.admin_reports, name="admin_reports"),
    path("manage/reports/<int:pk>/action/", views.admin_report_action, name="admin_report_action"),
    path("manage/reservation/<int:pk>/action/", views.admin_reservation_action, name="reservation_action"),
    path("manage/sales/", views.sales_history, name="sales_history"),
]
