# Generated by Django 6.0.2 on 2026-08-08 15:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("iot", "0012_remove_ai_registration_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Informational"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("missing_goat", "Missing Goat"),
                            ("person_detection", "Person / Intrusion Detection"),
                            ("device_anomaly", "Device / Sensor Anomaly"),
                            ("system", "System"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable origin, e.g. camera name or device name",
                        max_length=120,
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_notifications",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True,
                        help_text="Snapshot image captured at detection time",
                        null=True,
                        upload_to="person_detections/%Y/%m/%d/",
                    ),
                ),
                (
                    "source_label",
                    models.CharField(
                        blank=True,
                        help_text="Free-text source when no camera FK applies (e.g. uploaded frame)",
                        max_length=200,
                    ),
                ),
                (
                    "detection_type",
                    models.CharField(
                        choices=[
                            ("person", "Person Detected"),
                            ("unknown_person", "Unknown Person"),
                            ("face", "Face Detected"),
                        ],
                        default="person",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Detection confidence (0-1)"
                    ),
                ),
                ("bounding_boxes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewing", "Under Review"),
                            ("confirmed", "Confirmed Threat"),
                            ("dismissed", "Dismissed / False Alarm"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "review_state",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Unreviewed"),
                            ("reviewed", "Reviewed"),
                        ],
                        db_index=True,
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_detections",
                        to="iot.ipcamera",
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_detection",
                        to="security.notification",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_person_detections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person Detection",
                "verbose_name_plural": "Person Detections",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["-created_at"], name="security_no_created_bc5260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read", "-created_at"], name="security_no_is_read_0aa59f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_resolved", "-created_at"],
                name="security_no_is_reso_a1c525_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="security_no_severit_7066e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "-created_at"],
                name="security_no_notific_04bda6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["source_content_type", "source_object_id"],
                name="security_no_source__6f8b26_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("source_content_type", "source_object_id"),
                name="uniq_notification_per_source",
            ),
        ),
        migrations.AddIndex(
            model_name="persondetection",
            index=models.Index(
                fields=["-detected_at"], name="security_pe_detecte_cacfcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="persondetection",
            index=models.Index(
                fields=["detection_type", "-detected_at"],
                name="security_pe_detecti_ba2218_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="persondetection",
            index=models.Index(
                fields=["status", "-detected_at"], name="security_pe_status_734c39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="persondetection",
            index=models.Index(
                fields=["review_state", "-detected_at"],
                name="security_pe_review__e2123f_idx",
            ),
        ),
    ]
