# Generated by Django 5.0.14 on 2025-12-20 07:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level_grams', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_grams', models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(1)])),
                ('low_level_threshold', models.IntegerField(default=1000, help_text='Alert when feed level drops below this', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_refilled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.OneToOneField(limit_choices_to={'device_type': 'feeder'}, on_delete=django.db.models.deletion.CASCADE, related_name='feed_level', to='iot.device')),
            ],
        ),
        migrations.CreateModel(
            name='FeedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_time', models.TimeField(help_text='Time to dispense feed')),
                ('amount_grams', models.IntegerField(help_text='Amount of feed in grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('days_of_week', models.JSONField(default=list, help_text='List of day numbers (0=Sunday, 6=Saturday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feeder', models.ForeignKey(limit_choices_to={'device_type': 'feeder'}, on_delete=django.db.models.deletion.CASCADE, related_name='feed_schedules', to='iot.device')),
            ],
            options={
                'ordering': ['schedule_time'],
            },
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_dispensed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('scheduled', models.BooleanField(default=False, help_text='Was this a scheduled feeding or manual?')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='iot.device')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='feeding.feedschedule')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['feeder', '-timestamp'], name='feeding_fee_feeder__d3fefe_idx')],
            },
        ),
    ]
