# Generated by Django 5.0.14 on 2025-12-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlog',
            name='feeding_mode',
            field=models.CharField(choices=[('automated', 'Automated (Environment + ML)'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], db_index=True, default='manual', help_text='Primary classification of feeding trigger', max_length=20),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='goat_activity_score',
            field=models.FloatField(blank=True, help_text='0-1 scale, ML confidence', null=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='grass_health_index',
            field=models.FloatField(blank=True, help_text='0-1 scale, computer vision derived', null=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='grazing_behavior_score',
            field=models.FloatField(blank=True, help_text='0-1 scale, ML confidence', null=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='humidity_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='soil_moisture_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='temperature_celsius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedlog',
            name='trigger_reason',
            field=models.CharField(choices=[('drought_detected', 'Drought Detected'), ('low_soil_moisture', 'Low Soil Moisture'), ('high_temp_low_humidity', 'High Temperature + Low Humidity'), ('poor_grass_health', 'Poor Grass Health (Computer Vision)'), ('rainfall_detected', 'Rainfall Detected - Feeding Adjusted'), ('reduced_grazing', 'Reduced Grazing Behavior (ML)'), ('inactive_goats', 'Inactive Goats During Feeding Hours (ML)'), ('abnormal_behavior', 'Abnormal Goat Behavior (ML)'), ('ml_feeding_required', 'ML Flagged: Feeding Assistance Required'), ('time_based', 'Time-Based Schedule'), ('manual_override', 'Manual Override by User'), ('emergency', 'Emergency Feeding'), ('testing', 'System Testing')], default='manual_override', help_text='Specific reason why feeding was activated', max_length=50),
        ),
    ]
