# Generated by Django 5.1.15 on 2025-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_feedlog_feeding_mode_feedlog_goat_activity_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedFeedingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Master switch for automated feeding')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Automated Feeding Configuration',
                'verbose_name_plural': 'Automated Feeding Configuration',
            },
        ),
    ]
