# Generated by Django 6.0.1 on 2026-01-31 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_automatedfeedingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedlevel',
            name='distance_cm',
            field=models.FloatField(blank=True, help_text='Distance measured by ultrasonic sensor (cm)', null=True),
        ),
        migrations.AddField(
            model_name='feedlevel',
            name='percentage',
            field=models.IntegerField(blank=True, help_text='Feed level percentage from ultrasonic sensor (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
