# Generated by Django 6.0.1 on 2026-02-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0004_feedlevel_distance_cm_feedlevel_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Execution'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20),
        ),
    ]
