# Generated by Django 6.0.2 on 2026-03-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0005_alter_feedlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedlog',
            name='trigger_reason',
            field=models.CharField(choices=[('drought_detected', 'Drought Detected'), ('low_soil_moisture', 'Low Soil Moisture'), ('high_temp_low_humidity', 'High Temperature + Low Humidity'), ('poor_grass_health', 'Poor Grass Health (Computer Vision)'), ('rainfall_detected', 'Rainfall Detected - Feeding Adjusted'), ('reduced_grazing', 'Reduced Grazing Behavior (ML)'), ('inactive_goats', 'Inactive Goats During Feeding Hours (ML)'), ('abnormal_behavior', 'Abnormal Goat Behavior (ML)'), ('ml_feeding_required', 'ML Flagged: Feeding Assistance Required'), ('time_based', 'Time-Based Schedule'), ('manual_override', 'Manual Override by User'), ('physical_button', 'Physical Button Press'), ('emergency', 'Emergency Feeding'), ('testing', 'System Testing')], default='manual_override', help_text='Specific reason why feeding was activated', max_length=50),
        ),
    ]
